base_link:
  lidar:
    x: 0.0
    y: 0.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera0/camera_optical_link:
    x: 0.0
    y: 0.2
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
